import type { PcListing } from "@/types/pc";

export const MOCK_CANDIDATES: PcListing[] = [
  {
    id: "mock-1",
    title: "CyberPowerPC Gamer Xtreme VR Gaming PC (Intel Core i5, RTX 4060, 16GB RAM, 1TB NVMe SSD)",
    amazonUrl: "https://www.amazon.com/",
    priceUsd: 1099,
    cpu: "Intel Core i5",
    gpu: "NVIDIA GeForce RTX 4060",
    ramGb: 16,
    storageGb: 1024,
    storageType: "SSD",
    color: "black",
  },
  {
    id: "mock-2",
    title: "Skytech Gaming Chronos Mini (Ryzen 5, RTX 4060 Ti, 16GB RAM, 1TB SSD)",
    amazonUrl: "https://www.amazon.com/",
    priceUsd: 1299,
    cpu: "AMD Ryzen 5",
    gpu: "NVIDIA GeForce RTX 4060 Ti",
    ramGb: 16,
    storageGb: 1024,
    storageType: "SSD",
    color: "white",
  },
  {
    id: "mock-3",
    title: "iBUYPOWER Slate 8 Gaming Desktop (Intel Core i7, RTX 4070, 32GB RAM, 2TB NVMe SSD)",
    amazonUrl: "https://www.amazon.com/",
    priceUsd: 1899,
    cpu: "Intel Core i7",
    gpu: "NVIDIA GeForce RTX 4070",
    ramGb: 32,
    storageGb: 2048,
    storageType: "SSD",
    color: "black",
  },
  {
    id: "mock-4",
    title: "Dell Inspiron Desktop (Intel Core i5, 16GB RAM, 512GB SSD)",
    amazonUrl: "https://www.amazon.com/",
    priceUsd: 749,
    cpu: "Intel Core i5",
    ramGb: 16,
    storageGb: 512,
    storageType: "SSD",
    color: "silver",
  },
  {
    id: "mock-5",
    title: "HP Pavilion Desktop (Intel Core i3, 8GB RAM, 256GB SSD)",
    amazonUrl: "https://www.amazon.com/",
    priceUsd: 499,
    cpu: "Intel Core i3",
    ramGb: 8,
    storageGb: 256,
    storageType: "SSD",
    color: "black",
  },
];
